DROP TABLE IF EXISTS `pictures`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `pictures` (
  `IDpictures` int(11) NOT NULL AUTO_INCREMENT,
  `pictures`   blob(256),
  PRIMARY KEY (`IDpictures`)
  ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;


INSERT INTO `pictures` VALUES (1,'');

DELIMITER |
CREATE PROCEDURE showFrame(
IN IDpictures int(11)
)
BEGIN

SELECT pictures
FROM pictures
WHERE IDpictures = IDpictures;


END |
DELIMITER ;




DROP TABLE IF EXISTS `map`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `map` (
  `IDmap` int(11) NOT NULL AUTO_INCREMENT,
  `map`        varchar(2048),
  PRIMARY KEY (`IDmap`)
  ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `map` VALUES (1,'40
20
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HXXXX X XXXOOOXXXXXXXXXXXOXXXXXXXXXXXXXH
HXXOOXXXXXXXXX XXXXXXXXXXXXOXOXXXX  XXXH
HXXXXXXOXXXXXXXXXXXOOXOXXXXXXXXXXX  XXXH
HX  XXXVXXX  XXXOXXXXXXXXXVXXXXXXXXXXXXH
HXXXXOXXXXXX  XXXXXXXXXXXXXXXXXXXOXXXXXH
HXXXXXXXOOXXXXXXOOOXXXXXX XXXXXOXXXXXXXH
HXXXX X XXXXXXXXXXXXXXXXXXXXOOXX  XXOXXH
HHHHHHHHHHHHXXXOXXXXOXXXXXXXXXXXXXXOOXXH
HXXXXXVOXX XXXXXXXXXXXXXXXXXXOXXXXXXOXXH
HXXXXXOXXXXXXXXXXXOXXXXOXXXXXVOXXXXXXXXH
HHHHHHHHXXXXX  XXXXXXOXXXXXXXXXXXXXXXXXH
HXXXXXXOOOXOOXXXXXXXXXXXXXXXXXHHHHHHHHHH
HXXOOOXXXX XXXXXXXOOXVXXXXXXOXXHHHHHHHHH
HXXXXXXOXXXOOXVXXOOXXXXXXXOXXOXOOXXXXXXH
HOXXVXXXXXOOXXXXXOXXXXXXXXXX XXXXXXXXXXH
HOXXXXXXXHHHHHHHHHHHXXXXXOOXXOOXXXXXXXDH
HXXXOXXXXXXXOXXXVXXXXOOXXXXXXHXOXXXXXXXH
HXXXXXXOXXXXXXXXXXXXXXXXXXXXXHVXXO  XXXH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH');

DELIMITER |
CREATE PROCEDURE showMaps(
IN IDmapAdd int(11)
)

BEGIN

SELECT map
FROM map
WHERE IDmap = IDmapAdd;


END |
DELIMITER ;


